import pygame

# == PANTALLA ==
WIDTH = 768
HEIGHT = 576
GAME_TITLE = 'Crazy Snack'
SPRITE_SIZE = (96,96)
TILE_SIZE = 48

# == FIENTES ==
BIG_FONT = 36
MEDIUM_FONT = 16
SMALL_FONT = 14
FONT_NAME = 'BoldPixels'

# == CHEF ==
VELOCIDAD_CHEF = 4
DELAY_ANIMACION = 8

# == COCINA ==
MAX_ORDENES = 3 
TIEMPO_NIVEL_1 = 200
TIEMPO_NIVEL_2 = 230
TIEMPO_NIVEL_3 = 2500

# == RECETAS ==
PRIMERA_RECETA_DELAY = 5
INTERVALO_RECETA_MIN = 10
INTERVALO_RECETA_MAX = 20
PUNTOS_POR_INGREDIENTE = 50
TIEMPO_POR_INGREDIENTE = 20
TIEMPO_BASE_RECETA = 10
MAX_EXPIRACIONES = 3

# == ESTACIONES ==
TIEMPO_MEZCLA = 180
TIEMPO_LICUADO = 180
LIMITE_SHAKER = 3

# == EFECTOS ==
VELOCIDAD_PULSO = 0.2
VELOCIDAD_FADE = 5

# == PANTALLA RESULTADOS ==
DURACION_PANTALLA_R = 5
